# Foundry configuration for Cross-Chain Identity Hub

[profile.default]
solc = "0.8.19"
optimizer = true
optimizer_runs = 200
verbosity = 2
gas_reports = ["*"]
fuzz = { runs = 1000 }
coverage = true
timeout = 300

# Dependency remappings
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@ens/=lib/ens/",
    "@openzeppelin/=lib/openzeppelin-contracts/"
]

# RPC endpoints
[rpc_endpoints]
sepolia = "https://sepolia.infura.io/v3/${INFURA_API_KEY}"
mainnet = "https://mainnet.infura.io/v3/${INFURA_API_KEY}"
local = "http://localhost:8545"

# Etherscan API keys for verification
[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }

# Formatter configuration
[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"

# Linter configuration
[lint]
strict = true